#baseURL = "https://ljc.space/"
relativeURLs = true
language = "zh-CN"
title = "一蓑烟雨任平生"
theme = "maupassant"
publishDir ="../website"
hasCJKLanguage = true
defaultContentLanguage = "zh"

[author]
  name = "风竹"

[params]
  author = "风竹"
  subtitle = "C/C++、MFC、Go语言(golang)开发者"
  keywords = "golang,go语言,go语言笔记,博客,C,C++,mfc"
  description = "专注于IT互联网，包括但不限于Go语言(golang)、C/C++等"
  busuanzi = true
[params.utteranc]
    enable = true
    repo = "windzhu0514/windzhu0514.github.io"    # 存储评论的Repo，格式为 owner/repo
    #表示你选择以那种方式让github issue的评论和你的文章关联。
    #1. pathname 以路径的方式，推荐选项，这样你换域名的时候就不用担心评论找不到了
    #2. url 全链接URL路径的方式。
    #3. title 按页面title标题的方式。
    issueTerm = "pathname"  
    theme = "github-light" # 样式主题，有github-light和github-dark两种

  [menu]
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 2

[frontmatter]
toc = true
    
