name: hugo-deploy

on: 
  push:
    branches: 
    - master
  
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v2.5.1
      env:
         ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
         PUBLISH_BRANCH: gh-pages
         PUBLISH_DIR: ./public
         SCRIPT_MODE: true
